abdwg_jobeet_homepage:
    pattern:  /
    defaults: { _controller: AbdwgJobeetBundle:Job:index }

abdwg_Jobeet_job:
    resource: "@AbdwgJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job

abdwg_jobeet_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: AbdwgJobeetBundle:Category:show, page: 1 }

login:
    pattern:   /login
    defaults:  { _controller: AbdwgJobeetBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

abdwg_jobeet_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: "AbdwgJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml

abdwg_jobeet_affiliate:
    resource: "@AbdwgJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate
