abdwg_jobeet_homepage:
    pattern:  /
    defaults: { _controller: AbdwgJobeetBundle:Job:index }

abdwg_Jobeet_job:
    resource: "@AbdwgJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job

abdwg_jobeet_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: AbdwgJobeetBundle:Category:show, page: 1 }