# src\Abdwg\JobeetBundle\Resources\config\routing.yml
login:
    pattern:   /login
    defaults:  { _controller: AbdwgJobeetBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

abdwg_jobeet_homepage:
    pattern:  /{_locale}/
    defaults: { _controller: AbdwgJobeetBundle:Job:index }
    requirements:
        _locale: en|zh

abdwg_Jobeet_nonlocalized:
    pattern:  /
    defaults: { _controller: "AbdwgJobeetBundle:Job:index" }

abdwg_Jobeet_job:
    resource: "@AbdwgJobeetBundle/Resources/config/routing/job.yml"
    prefix: /{_locale}/job
    requirements:
        _locale: en|zh

abdwg_jobeet_category:
    pattern:  /{_locale}/category/{slug}/{page}
    defaults: { _controller: AbdwgJobeetBundle:Category:show, page: 1 }
    requirements:
        _locale: en|zh

abdwg_jobeet_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: "AbdwgJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml

abdwg_jobeet_affiliate:
    resource: "@AbdwgJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix:   /{_locale}/affiliate
    requirements:
        _locale: en|zh

abdwg_jobeet_changeLanguage:
    pattern: /change_language
    defaults: { _controller: "AbdwgJobeetBundle:Default:changeLanguage" }


