parameters:
#    abdwg_jobeet.example.class: Abdwg\JobeetBundle\Example

services:
#    abdwg_jobeet.example:
#        class: %abdwg_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
