parameters:
#    abdwg_jobeet.example.class: Abdwg\JobeetBundle\Example

services:
    abdwg.jobeet.admin.category:
        class: Abdwg\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments:
            - ~
            - Abdwg\JobeetBundle\Entity\Category
            - 'AbdwgJobeetBundle:CategoryAdmin'

    abdwg.jobeet.admin.job:
        class: Abdwg\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments:
            - ~
            - Abdwg\JobeetBundle\Entity\Job
            - 'AbdwgJobeetBundle:JobAdmin'

    abdwg.jobeet.admin.affiliate:
        class: Abdwg\JobeetBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Affiliates }
        arguments:
            - ~
            - Abdwg\JobeetBundle\Entity\Affiliate
            - 'AbdwgJobeetBundle:AffiliateAdmin'