abdwg_job:
    pattern:  /
    defaults: { _controller: "AbdwgJobeetBundle:Job:index" }

abdwg_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "AbdwgJobeetBundle:Job:show" }
    requirements:
        id:  \d+

abdwg_job_new:
    pattern:  /new
    defaults: { _controller: "AbdwgJobeetBundle:Job:new" }

abdwg_job_create:
    pattern:  /create
    defaults: { _controller: "AbdwgJobeetBundle:Job:create" }
    requirements: { _method: post }

abdwg_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AbdwgJobeetBundle:Job:edit" }

abdwg_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "AbdwgJobeetBundle:Job:update" }
    requirements: { _method: post|put }

abdwg_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AbdwgJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
